version: '3'
services:
  app:
    container_name: pradityahendrik-shopee
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: shopee
    ports:
    - "3308:3306"